### ISSUE TITLE
Let's figure out the way to make this plugin ClearLinux friendly

### ISSUE THREAD

**Issue by mpurzynski** [J-Gras/bro-af_packet-plugin#10]
ClearLinux included Bro 2.6 recently, I'd like to help make this plugin upstream compatibile

https://github.com/clearlinux-pkgs/bro

**Comment by J-Gras** [comment]
What has to be done to achieve compatibility?

**Comment by mpurzynski** [comment]
So first of all, we cannot be dependent on the Zeek source tree, but rather on parts of Zeek installed in the system already.

Let's identify the components of Zeek that are necessary for the af_packet plugin to build.

--bro-dist=DIR             Path to Bro source tree

What are those files that are necessary from the source tree?

**Comment by mpurzynski** [comment]
Excellent. I was able to build the af_packet plugin without the Zeek source directory (2.6), when I installed Zeek manually.

I cannot repeat that with upstream Zeek, so that makes me think we're missing something (most likely upstream in ClearLinux, not really here). It would be very useful to know what is this plugin expects.

./configure --install-root=/usr/lib/bro/plugins --with-kernel=../linux-5.0 

Build Directory        : build
Bro Source Directory   : 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Broker (missing: BROKER_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/bro/cmake/FindBroker.cmake:35 (find_package_handle_standard_args)
  /usr/share/bro/cmake/BroPluginDynamic.cmake:119 (find_package)
  /usr/share/bro/cmake/BroPlugin.cmake:16 (include)
  CMakeLists.txt:6 (include)

Do you know what header files is af_packet looking for?

**Comment by mpurzynski** [comment]
I found the broker.hh on another system and implanted it into /usr/include/broker/broker.hh

So that's one thing that upstream is missing. Another problem is here


ake[3]: Entering directory '/home/michal/bro-af_packet-plugin-1.4.0/build'
[ 27%] Building CXX object CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/src/Plugin.cc.o
In file included from /home/michal/bro-af_packet-plugin-1.4.0/src/Plugin.cc:2:
/home/michal/bro-af_packet-plugin-1.4.0/src/Plugin.h:5:10: fatal error: plugin/Plugin.h: No such file or directory
 #include <plugin/Plugin.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

What's interesting - this header file is part of the af_packet plugin itself

/home/michal/bro-af_packet-plugin-1.4.0 # find . -name Plugin.h

./src/Plugin.h

but it's definitely not at 'plugin/Plugin.h'

**Comment by J-Gras** [comment]
I guess it's about the following file: https://github.com/zeek/zeek/blob/master/src/plugin/Plugin.h
Strange that this cannot be found.

**Comment by mpurzynski** [comment]
Turns out, this file, along with broker.hh and other files are included in the 

https://download.clearlinux.org/releases/current/clear/x86_64/os/Packages/bro-dev-2.6.1-5.x86_64.rpm

That's excellent news, I managed to build the af_packet plugin against the upstream'ed Zeek now in ClearLinux. Makes me think autospec-ing should be possible now.

**Comment by J-Gras** [comment]
Nice! Feel free to reopen the issue if there is anything that has to be changed in the plugin.
