### ISSUE TITLE
Buffer Size?

### ISSUE THREAD

**Issue by TOoSmOotH** [J-Gras/bro-af_packet-plugin#4]
Is there any way to set the buffer size in the node.cfg?

**Comment by J-Gras** [comment]
Right now you would need to set the buffer size in a Bro script. Do you think it is common to configure different buffer sizes for different nodes of a cluster?

**Comment by TOoSmOotH** [comment]
I am new to af_packet but when I used pf_ring I commonly used to change the ring buffer based on how well the box is performing. My installs are mostly distributed vs a single large cluster so I have different size boxes spread out all over the enterprise. I can modify the actual script but changing the node.cfg would make it easier. Have you played with adjusting the buffer size in the script? Do you notice any differences when increasing it on busier systems?

**Comment by J-Gras** [comment]
Unfortunately I haven't benchmarked the effect of the buffer size so far. I created a branch and added the option to the broctl plugin so that it can be configured in node.cfg. Have a look at buffer-size or just use ``bro-pkg install bro-af_packet-plugin --version buffer-size``. If you can verify that it works as expected, I am happy to merge that change into master.

**Comment by TOoSmOotH** [comment]
I'll give it a test.. Do you know what the default size is? I can do some load testing.

**Comment by J-Gras** [comment]
The default size is set to ``128 * 1024 * 1024`` (128MB) in ``init.bro``. I am curious to hear about your results!

**Comment by TOoSmOotH** [comment]
How should I represent that in the node.cfg? 128000000?

**Comment by J-Gras** [comment]
You should also be able to write ``128*1024*1024`` as it gets written to a bro-script.

**Comment by TOoSmOotH** [comment]
So I cranked up the buffer to 1 gig and I am seeing better performance. Do you know where netstats is getting its counters from? The netstats don't reset when you restart Bro.

**Comment by J-Gras** [comment]
What do you mean by "better performance"? Less packet drops?

If I am not mistaken, ``broctl netstats`` reads out Bro's packet counters, which are written by the plugin. It might be worth to turn on ``stats.log``.
