### ISSUE TITLE
cmake can't find header files on Ubuntu

### ISSUE THREAD

**Issue by grantcurell** [J-Gras/bro-af_packet-plugin#7]
```
sudo ./configure --bro-dist=./bro --with-latest-kernel
Build Directory        : build
Bro Source Directory   : /home/grant/bro-af_packet-plugin/bro
CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    BroPlugin


CMake Warning at CMakeLists.txt:8 (find_package):
  By not providing "FindKernelHeaders.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KernelHeaders", but CMake did not find one.

  Could not find a package configuration file provided by "KernelHeaders"
  with any of the following names:

    KernelHeadersConfig.cmake
    kernelheaders-config.cmake

  Add the installation prefix of "KernelHeaders" to CMAKE_PREFIX_PATH or set
  "KernelHeaders_DIR" to a directory containing one of the above files.  If
  "KernelHeaders" provides a separate development package or SDK, be sure it
  has been installed.


CMake Error at CMakeLists.txt:22 (message):
  Kernel headers not found.


-- Configuring incomplete, errors occurred!
See also "/home/grant/bro-af_packet-plugin/build/CMakeFiles/CMakeOutput.log".
```

---------------------------------------

I successfully installed the kernel headers with `sudo apt-get install -y cmake linux-headers-$(uname -r)`. I'm not super familiar with cmake and am not sure what the `find_package` command is doing, but it can't find the header files on Ubuntu.

**Comment by grantcurell** [comment]
Tried the same thing on Fedora and received the same error using bro-pkg which under the hood looks to be using the regular configure file. Appears that building the plugin is currently broken.

**Comment by grantcurell** [comment]
Was able to fix the kernel header problem by adding the line:

`SET(CMAKE_MODULE_PATH "/root/bro-af_packet-plugin/cmake")`

to CMakelists.txt, but that stillleaves me with:

```
Build Directory        : build
Bro Source Directory   : /root/bro
CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    BroPlugin


CMake Error at CMakeLists.txt:14 (bro_plugin_begin):
  Unknown CMake command "bro_plugin_begin".


-- Configuring incomplete, errors occurred!
See also "/root/bro-af_packet-plugin/build/CMakeFiles/CMakeOutput.log".
```

**Comment by grantcurell** [comment]
Fixed and pull request submitted at: https://github.com/J-Gras/bro-af_packet-plugin/pull/8

**Comment by J-Gras** [comment]
> Tried the same thing on Fedora and received the same error using bro-pkg which under the hood looks to be using the regular configure file. Appears that building the plugin is currently broken.

Indeed bro-pkg uses the same cmake process to build the plugin.

> Fixed and pull request submitted at: #8

Thanks, I will review and merge next week!

**Comment by grantcurell** [comment]
I'm working on a docker container and I noticed that my fix works and the FindKernelModules runs in my containerized environment (it's the systemd container), but the module itself doesn't find the kernel modules unless you add --with-latest-kernel. Not sure if that's what is supposed to happen. Haven't looked at the code that closely. I did see @dcode over on the rock project has a patch for it https://gist.github.com/dcode/5e58fed4df358983738244ade4d100e3

**Comment by J-Gras** [comment]
I have set up an Ubuntu and tried to reproduce the issue without success. Neither using absolute nor relative path for ``--bro-dist`` lead to any issues. I have been using CMake version 3.10.2 on Ubuntu Server 18.04 LTS. However, as Bro 2.6 now provides include files, I will switch to the new version of the configure script so that building the plugin does not rely on Bro sources anymore. Feel free to reopen the issue if you keep having trouble on fresh installs.

> I did see @dcode over on the rock project has a patch for it
 
The fix by @dcode you found was actually the inspiration for ``--with-latest-kernel`` (see #2).
